### ISSUE TITLE
KeyError: 5.0

### ISSUE THREAD

**Issue by chiragsanghvi10** [kamalkraj/ALBERT-TF2.0#14]
Hi, I am working on STS-B data set and I am executing the following commands in Ubuntu

`export GLUE_DIR=glue_data
export ALBERT_DIR=model_configs/large

export TASK_NAME=STS
export OUTPUT_DIR=stsb_processed
mkdir $OUTPUT_DIR

python create_finetuning_data.py \
 --input_data_dir=${GLUE_DIR}/ \
 --spm_model_file=${ALBERT_DIR}/vocab/30k-clean.model \
 --train_data_output_path=${OUTPUT_DIR}/${TASK_NAME}_train.tf_record \
 --eval_data_output_path=${OUTPUT_DIR}/${TASK_NAME}_eval.tf_record \
 --meta_data_file_path=${OUTPUT_DIR}/${TASK_NAME}_meta_data \
 --fine_tuning_task_type=classification --max_seq_length=128 \
 --classification_task_name=${TASK_NAME}
`
### Error message:
`I1206 14:39:44.645808 139799230306112 classifier_data_lib.py:761] Writing example 0 of 5749
Traceback (most recent call last):
  File "create_finetuning_data.py", line 149, in <module>
    app.run(main)
  File "/home/chirag/venv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/chirag/venv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "create_finetuning_data.py", line 137, in main
    input_meta_data = generate_classifier_dataset()
  File "create_finetuning_data.py", line 122, in generate_classifier_dataset
    do_lower_case=FLAGS.do_lower_case)
  File "/home/chirag/git/ALBERT-TF2.0/classifier_data_lib.py", line 835, in generate_tf_record_from_data_file
    train_data_output_path)
  File "/home/chirag/git/ALBERT-TF2.0/classifier_data_lib.py", line 764, in file_based_convert_examples_to_features
    max_seq_length, tokenizer)
  File "/home/chirag/git/ALBERT-TF2.0/classifier_data_lib.py", line 732, in convert_single_example
    label_id = label_map[example.label]
KeyError: 5.0
`

Any idea on why I am getting KeyError ? Thanks in advance.

**Comment by kamalkraj** [comment]
@chiragsanghvi10 
Fixed 8d0cc211361e81a648bf846d8ec84225273db0e4

**Comment by chiragsanghvi10** [comment]
Hi @kamalkraj I was able to execute this, Thank you :)
